In [1]:
## Data Collection: Load csv files and check contents

import pandas as pd
import glob

# Set pandas option to display all columns
pd.set_option('display.max_columns', None)

# Define the path to your CSV files
csv_files = glob.glob('fuel_prices_*.csv')  # Assumes all files start with 'fuel_price_' and are in the current directory

# Load all CSV files into a list of DataFrames
df_list = [pd.read_csv(file) for file in csv_files]

# Concatenate all DataFrames into one DataFrame
df = pd.concat(df_list, ignore_index=True)

# Display the shape of the combined DataFrame to verify
print(df.shape)
df.head(20)

(469336, 12)

,SiteId,Site_Name,Site_Brand,Sites_Address_Line_1,Site_Suburb,Site_State,Site_Post_Code,Site_Latitude,Site_Longitude,Fuel_Type,Price,TransactionDateutc
0,61401007,7-Eleven Coomera,7 Eleven,Pacific Highway,Coomera,QLD,4209,-27.868591,153.314206,e10,1879,31/03/2024 18:20
1,61401007,7-Eleven Coomera,7 Eleven,Pacific Highway,Coomera,QLD,4209,-27.868591,153.314206,e10,2339,16/04/2024 04:46
2,61401007,7-Eleven Coomera,7 Eleven,Pacific Highway,Coomera,QLD,4209,-27.868591,153.314206,LPG,1119,31/03/2024 18:20
3,61401007,7-Eleven Coomera,7 Eleven,Pacific Highway,Coomera,QLD,4209,-27.868591,153.314206,Premium Diesel,1999,31/03/2024 18:20
4,61401007,7-Eleven Coomera,7 Eleven,Pacific Highway,Coomera,QLD,4209,-27.868591,153.314206,PULP 98 RON,2109,31/03/2024 18:20
5,61401007,7-Eleven Coomera,7 Eleven,Pacific Highway,Coomera,QLD,4209,-27.868591,153.314206,PULP 98 RON,2569,16/04/2024 04:46
6,61401007,7-Eleven Coomera,7 Eleven,Pacific Highway,Coomera,QLD,4209,-27.868591,153.314206,Unleaded,1899,31/03/2024 18:20
7,61401007,7-Eleven Coomera,7 Eleven,Pacific Highway,Coomera,QLD,4209,-27.868591,153.314206,Unleaded,2359,16/04/2024 04:46
8,61401008,EG Ampol Oxenford,EG Ampol,116 Old Pacific Highway,Oxenford,QLD,4210,-27.891217,153.313369,e10,1849,31/03/2024 14:00
9,61401008,EG Ampol Oxenford,EG Ampol,116 Old Pacific Highway,Oxenford,QLD,4210,-27.891217,153.313369,e10,1859,09/04/2024 01:15
10,61401008,EG Ampol Oxenford,EG Ampol,116 Old Pacific Highway,Oxenford,QLD,4210,-27.891217,153.313369,e10,2339,16/04/2024 08:30
11,61401008,EG Ampol Oxenford,EG Ampol,116 Old Pacific Highway,Oxenford,QLD,4210,-27.891217,153.313369,e10,2219,25/04/2024 22:00
12,61401008,EG Ampol Oxenford,EG Ampol,116 Old Pacific Highway,Oxenford,QLD,4210,-27.891217,153.313369,e10,2199,26/04/2024 08:30
13,61401008,EG Ampol Oxenford,EG Ampol,116 Old Pacific Highway,Oxenford,QLD,4210,-27.891217,153.313369,Premium Diesel,2069,31/03/2024 14:00
14,61401008,EG Ampol Oxenford,EG Ampol,116 Old Pacific Highway,Oxenford,QLD,4210,-27.891217,153.313369,Premium Diesel,2059,01/04/2024 22:00
15,61401008,EG Ampol Oxenford,EG Ampol,116 Old Pacific Highway,Oxenford,QLD,4210,-27.891217,153.313369,Premium Diesel,2069,09/04/2024 00:30
16,61401008,EG Ampol Oxenford,EG Ampol,116 Old Pacific Highway,Oxenford,QLD,4210,-27.891217,153.313369,Premium Diesel,2079,10/04/2024 23:15
17,61401008,EG Ampol Oxenford,EG Ampol,116 Old Pacific Highway,Oxenford,QLD,4210,-27.891217,153.313369,Premium Diesel,2069,15/04/2024 02:30
18,61401008,EG Ampol Oxenford,EG Ampol,116 Old Pacific Highway,Oxenford,QLD,4210,-27.891217,153.313369,PULP 95/96 RON,2019,31/03/2024 14:00
19,61401008,EG Ampol Oxenford,EG Ampol,116 Old Pacific Highway,Oxenford,QLD,4210,-27.891217,153.313369,PULP 95/96 RON,2029,09/04/2024 01:15

In [2]:
# Check for missing values (NaN or null) in each column
missing_values = df.isnull().sum()
print(missing_values)

SiteId                  0
Site_Name               0
Site_Brand              0
Sites_Address_Line_1    0
Site_Suburb             0
Site_State              0
Site_Post_Code          0
Site_Latitude           0
Site_Longitude          0
Fuel_Type               0
Price                   0
TransactionDateutc      0
dtype: int64

In [3]:
# Check for infinite values
infinite_values = df.isin([float('inf'), float('-inf')]).sum()
print(infinite_values)

SiteId                  0
Site_Name               0
Site_Brand              0
Sites_Address_Line_1    0
Site_Suburb             0
Site_State              0
Site_Post_Code          0
Site_Latitude           0
Site_Longitude          0
Fuel_Type               0
Price                   0
TransactionDateutc      0
dtype: int64

In [4]:
# Check data types of each column
print(df.dtypes)

SiteId                    int64
Site_Name                object
Site_Brand               object
Sites_Address_Line_1     object
Site_Suburb              object
Site_State               object
Site_Post_Code            int64
Site_Latitude           float64
Site_Longitude          float64
Fuel_Type                object
Price                     int64
TransactionDateutc       object
dtype: object

In [5]:
# Set pandas option to display all columns
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)        # Set display width to avoid line breaks

# Check for duplicates based on specific columns (e.g., SiteId, Site_Name)
duplicates_subset = df[df.duplicated(subset=['SiteId', 'Fuel_Type', 'Price', 'TransactionDateutc'])]
print("Duplicates based on SiteId, Fuel_Type, Price, and TransactionDateutc:\n", duplicates_subset)

Duplicates based on SiteId, Fuel_Type, Price, and TransactionDateutc:
           SiteId               Site_Name    Site_Brand   Sites_Address_Line_1 Site_Suburb Site_State  Site_Post_Code  Site_Latitude  Site_Longitude    Fuel_Type  Price TransactionDateutc
87122   61478032    Pearl Energy Pimpama  Pearl Energy      404 Yawalpah Road     Coomera        QLD            4209     -27.826603      153.330178  PULP 98 RON   1825   24/09/2024 22:22
156991  61478091         Mobil Berserker         Mobil  12 Queen Elizabeth Dr   Berserker        QLD            4701     -23.371540      150.519524          e10   1895   12/05/2024 11:06
200634  61477126  Seaforth General Store         Ampol            8 George St    Seaforth        QLD            4741     -20.901699      148.967698     Unleaded   1926   01/07/2024 04:25
358960  61478032    Pearl Energy Pimpama  Pearl Energy      404 Yawalpah Road     Coomera        QLD            4209     -27.826603      153.330178       Diesel   1935   05/02/2024 12:45

In [6]:
# Check for duplicates across all columns
duplicates_all_columns = df[df.duplicated(keep=False)]
print("Duplicates across all columns:\n", duplicates_all_columns)

Duplicates across all columns:
           SiteId               Site_Name    Site_Brand   Sites_Address_Line_1 Site_Suburb Site_State  Site_Post_Code  Site_Latitude  Site_Longitude    Fuel_Type  Price TransactionDateutc
87120   61478032    Pearl Energy Pimpama  Pearl Energy      404 Yawalpah Road     Coomera        QLD            4209     -27.826603      153.330178  PULP 98 RON   1825   24/09/2024 22:22
87122   61478032    Pearl Energy Pimpama  Pearl Energy      404 Yawalpah Road     Coomera        QLD            4209     -27.826603      153.330178  PULP 98 RON   1825   24/09/2024 22:22
156989  61478091         Mobil Berserker         Mobil  12 Queen Elizabeth Dr   Berserker        QLD            4701     -23.371540      150.519524          e10   1895   12/05/2024 11:06
156991  61478091         Mobil Berserker         Mobil  12 Queen Elizabeth Dr   Berserker        QLD            4701     -23.371540      150.519524          e10   1895   12/05/2024 11:06
200632  61477126  Seaforth General Store         Ampol            8 George St    Seaforth        QLD            4741     -20.901699      148.967698     Unleaded   1926   01/07/2024 04:25
200634  61477126  Seaforth General Store         Ampol            8 George St    Seaforth        QLD            4741     -20.901699      148.967698     Unleaded   1926   01/07/2024 04:25
358958  61478032    Pearl Energy Pimpama  Pearl Energy      404 Yawalpah Road     Coomera        QLD            4209     -27.826603      153.330178       Diesel   1935   05/02/2024 12:45
358960  61478032    Pearl Energy Pimpama  Pearl Energy      404 Yawalpah Road     Coomera        QLD            4209     -27.826603      153.330178       Diesel   1935   05/02/2024 12:45

In [7]:
# Ensure Price is numeric
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')

# Ensure TransactionDateutc is a datetime object
#df['TransactionDateutc'] = pd.to_datetime(df['TransactionDateutc'], errors='coerce')
df['TransactionDateutc'] = pd.to_datetime(df['TransactionDateutc'], format='%d/%m/%Y %H:%M', errors='coerce')

# Check for duplicates again
duplicates_subset = df[df.duplicated(subset=['SiteId', 'Fuel_Type', 'Price', 'TransactionDateutc'])]
print(duplicates_subset)

          SiteId               Site_Name    Site_Brand   Sites_Address_Line_1 Site_Suburb Site_State  Site_Post_Code  Site_Latitude  Site_Longitude    Fuel_Type  Price  TransactionDateutc
87122   61478032    Pearl Energy Pimpama  Pearl Energy      404 Yawalpah Road     Coomera        QLD            4209     -27.826603      153.330178  PULP 98 RON   1825 2024-09-24 22:22:00
156991  61478091         Mobil Berserker         Mobil  12 Queen Elizabeth Dr   Berserker        QLD            4701     -23.371540      150.519524          e10   1895 2024-05-12 11:06:00
200634  61477126  Seaforth General Store         Ampol            8 George St    Seaforth        QLD            4741     -20.901699      148.967698     Unleaded   1926 2024-07-01 04:25:00
358960  61478032    Pearl Energy Pimpama  Pearl Energy      404 Yawalpah Road     Coomera        QLD            4209     -27.826603      153.330178       Diesel   1935 2024-02-05 12:45:00

In [8]:
# Drop duplicates, keeping the first occurrence
df_cleaned = df.drop_duplicates(keep='first')

# Verify that duplicates are removed
print("Number of rows after dropping duplicates:", df_cleaned.shape[0])

Number of rows after dropping duplicates: 469332

In [9]:
# Check if any duplicates remain in the cleaned DataFrame
duplicates_after_cleaning = df_cleaned[df_cleaned.duplicated(keep=False)]
print("Remaining duplicates after cleaning:\n", duplicates_after_cleaning)

Remaining duplicates after cleaning:
 Empty DataFrame
Columns: [SiteId, Site_Name, Site_Brand, Sites_Address_Line_1, Site_Suburb, Site_State, Site_Post_Code, Site_Latitude, Site_Longitude, Fuel_Type, Price, TransactionDateutc]
Index: []

In [10]:
# Describe the numeric columns (shows min, max, mean, etc.)
print(df.describe())

             SiteId  Site_Post_Code  Site_Latitude  Site_Longitude          Price             TransactionDateutc
count  4.693360e+05   469336.000000  469336.000000   469336.000000  469336.000000                         469336
mean   6.142713e+07     4299.529863     -26.654728      152.386528    2056.419857  2024-05-28 02:33:20.868375552
min    6.129015e+07     2486.000000     -28.973467      138.117892       1.000000            2023-12-31 14:00:00
25%    6.140162e+07     4117.000000     -27.645205      152.792164    1879.000000            2024-03-22 00:30:15
50%    6.140225e+07     4212.000000     -27.504950      153.023236    1999.000000            2024-06-03 08:15:00
75%    6.147714e+07     4503.000000     -27.202591      153.111388    2149.000000            2024-08-02 08:26:15
max    6.147825e+07     4895.000000      -9.750595      153.541441    9999.000000            2024-09-30 13:12:00
std    3.512798e+04      246.269662       2.431686        1.809363     582.915566                            NaN

In [11]:
# Check unique values for categorical columns
print(df['Site_Brand'].unique())
print(df['Fuel_Type'].unique())

['7 Eleven' 'EG Ampol' 'Coles Express' 'Ampol' 'Caltex' 'Freedom Fuels'
 'Metro Fuel' 'BP' 'Pearl Energy' 'Independent' 'Liberty' 'Shell'
 'Puma Energy' 'United' 'Unknown' 'Pacific Petroleum' 'Reddy Express'
 'Mobil' 'Pacific Fuel Solutio' 'Enhance' 'Lowes' 'Astron' 'IOR Petroleum'
 'Choice' 'Costco' 'Perrys' 'U-Go' 'Atlas Fuel' 'Matilda']
['e10' 'LPG' 'Premium Diesel' 'PULP 98 RON' 'Unleaded' 'PULP 95/96 RON'
 'Diesel' 'e85' 'OPAL']

In [12]:
# Filter rows where Site_Brand is 'Unknown' and get distinct SiteId with other info
distinct_unknown_sites = df[df['Site_Brand'] == 'Unknown'][['SiteId', 'Site_Name', 'Sites_Address_Line_1', 'Site_Suburb', 'Site_State', 'Site_Post_Code', 'Site_Latitude', 'Site_Longitude']].drop_duplicates()

# Print distinct SiteId along with other site information
print(distinct_unknown_sites)

          SiteId                          Site_Name                Sites_Address_Line_1     Site_Suburb Site_State  Site_Post_Code  Site_Latitude  Site_Longitude
1783    61401206           Ampol Foodary Park Ridge       3726-3730 Mt Lindesay Highway      Park Ridge        QLD            4125     -27.696775      153.038071
2238    61401248                    Puma Strathpine                     116 Gympie Road      Strathpine        QLD            4500     -27.313978      152.992774
6664    61401613            Ampol Foodary Cleveland      209 Bloomfield St Cnr Ross Ctr       Cleveland        QLD            4163     -27.532546      153.266347
6735    61401620           Ampol Foodary Loganholme                     80 Bryants Road      Loganholme        QLD            4129     -27.662977      153.179704
154561  61478008  Fresh Trading Co. Mobil Rasmussen                    2-4 Santal Drive       Rasmussen        QLD            4815     -19.352689      146.731468
156124  61478051     Fresh Trading Co. Mobil Gympie                      47 Pine Street          Gympie        QLD            4570     -26.181673      152.652007
157248  61478098       Fresh Trading Co. St Helens.              870 Saltwater Creek Rd       St Helens        QLD            4650     -25.504614      152.711570
159019  61478229                   EG Ampol Baringa                        2 Symonds Wy         Baringa        QLD            4551     -26.811563      153.068923
167962  61401391              Ampol Foodary Toowong                     581 Milton Road         Toowong        QLD            4066     -27.478393      152.985913
214793  61478236           NightOwl Shell Karawatha                       19 Forest Way       Karawatha        QLD            4117     -27.651203      153.075828
227286  61401656       Matilda Blue Fuel Caboolture                  22 Beerburrum Road      Caboolture        QLD            4510     -27.082012      152.952088
272207  61401489              Ampol Foodary Ipswich                      10 Pine Street   North Ipswich        QLD            4305     -27.606817      152.762458
303148  61477102                    Perrys Jandowae                      31 High Street        Jandowae        QLD            4410     -26.779606      151.108921
303212  61477119           Caltex Marlborough North                     13 Perkins Road     Marlborough        QLD            4705     -22.821680      149.891454
306408  61477717           Freedom Fuels Harristown             529-543 Alderley Street      Harristown        QLD            4350     -27.580309      151.920598
402493  61402752       Ampol Kunda Park Diesel Stop                69 Enterprise Street      Kunda Park        QLD            4556     -26.670055      153.026641
420280  61477844              Imbil Friendly Grocer                      100 Yabba Road           Imbil        QLD            4570     -26.460058      152.674999
436174  61401588            7-Eleven Victoria Point  439-447 Cleveland-Redland Bay Road  Victoria Point        QLD            4165     -27.584359      153.281092
455766  61470145                 Mobil Port Douglas                    13 Warner Street    Port Douglas        QLD            4871     -16.483003      145.462489

In [13]:
print(df[df['SiteId']==61401206])

          SiteId                 Site_Name Site_Brand           Sites_Address_Line_1 Site_Suburb Site_State  Site_Post_Code  Site_Latitude  Site_Longitude    Fuel_Type  Price  TransactionDateutc
1783    61401206  Ampol Foodary Park Ridge    Unknown  3726-3730 Mt Lindesay Highway  Park Ridge        QLD            4125     -27.696775      153.038071          e10   1979 2024-03-31 14:01:00
1784    61401206  Ampol Foodary Park Ridge    Unknown  3726-3730 Mt Lindesay Highway  Park Ridge        QLD            4125     -27.696775      153.038071          e10   1959 2024-04-01 20:53:00
1785    61401206  Ampol Foodary Park Ridge    Unknown  3726-3730 Mt Lindesay Highway  Park Ridge        QLD            4125     -27.696775      153.038071          e10   1939 2024-04-03 19:08:00
1786    61401206  Ampol Foodary Park Ridge    Unknown  3726-3730 Mt Lindesay Highway  Park Ridge        QLD            4125     -27.696775      153.038071          e10   1919 2024-04-09 07:12:00
1787    61401206  Ampol Foodary Park Ridge    Unknown  3726-3730 Mt Lindesay Highway  Park Ridge        QLD            4125     -27.696775      153.038071          e10   2339 2024-04-10 05:56:00
...          ...                       ...        ...                            ...         ...        ...             ...            ...             ...          ...    ...                 ...
431916  61401206  Ampol Foodary Park Ridge      Ampol  3726-3730 Mt Lindesay Highway  Park Ridge        QLD            4125     -27.696775      153.038071  PULP 98 RON   2339 2024-01-05 04:40:00
431917  61401206  Ampol Foodary Park Ridge      Ampol  3726-3730 Mt Lindesay Highway  Park Ridge        QLD            4125     -27.696775      153.038071  PULP 98 RON   2319 2024-01-28 21:58:00
431918  61401206  Ampol Foodary Park Ridge      Ampol  3726-3730 Mt Lindesay Highway  Park Ridge        QLD            4125     -27.696775      153.038071     Unleaded   1759 2023-12-31 14:01:00
431919  61401206  Ampol Foodary Park Ridge      Ampol  3726-3730 Mt Lindesay Highway  Park Ridge        QLD            4125     -27.696775      153.038071     Unleaded   2139 2024-01-05 04:40:00
431920  61401206  Ampol Foodary Park Ridge      Ampol  3726-3730 Mt Lindesay Highway  Park Ridge        QLD            4125     -27.696775      153.038071     Unleaded   2119 2024-01-28 21:58:00

[417 rows x 12 columns]

In [14]:
# Ensure that the TransactionDateutc column is in datetime format
df['TransactionDateutc'] = pd.to_datetime(df['TransactionDateutc'], errors='coerce')

# Sort the DataFrame by SiteId and TransactionDateutc
df_sorted = df.sort_values(by=['SiteId', 'TransactionDateutc'])

# Get the last row for each SiteId
last_rows_per_site = df_sorted.groupby('SiteId').tail(1)

# Print the last rows for each SiteId
print(last_rows_per_site)

          SiteId                    Site_Name     Site_Brand     Sites_Address_Line_1    Site_Suburb Site_State  Site_Post_Code  Site_Latitude  Site_Longitude       Fuel_Type  Price  TransactionDateutc
361651  61290151                Liberty Surat        Liberty       61 Burrowes Street          Surat        QLD            4417     -27.151687      149.067742          Diesel   1899 2024-08-23 23:49:00
31444   61291313           Lowes Mungindi Opt             BP        126 Barwon Street       Mungindi        QLD            4497     -28.973467      148.983829        Unleaded   1850 2024-09-18 22:00:00
31489   61401007             7-Eleven Coomera       7 Eleven          Pacific Highway        Coomera        QLD            4209     -27.868591      153.314206        Unleaded   1999 2024-09-30 04:44:00
31508   61401008            EG Ampol Oxenford       EG Ampol  116 Old Pacific Highway       Oxenford        QLD            4210     -27.891217      153.313369  Premium Diesel   1839 2024-09-30 03:15:00
31624   61401010         Coles Express Nerang  Coles Express         6-8 Ferry Street         Nerang        QLD            4211     -27.990022      153.337183        Unleaded   1999 2024-09-26 01:30:00
...          ...                          ...            ...                      ...            ...        ...             ...            ...             ...             ...    ...                 ...
91044   61478236     NightOwl Shell Karawatha          Shell            19 Forest Way      Karawatha        QLD            4117     -27.651203      153.075828        Unleaded   1799 2024-09-30 07:10:00
91053   61478242         Caltex Rainbow Beach         Caltex      66 Rainbow Beach Rd  Rainbow Beach        QLD            4581     -25.910619      153.089130  Premium Diesel   1719 2024-09-23 21:09:00
91094   61478243  NightOwl BP Anderson Street             BP        66-68 Anderson St        Manunda        QLD            4870     -16.914498      145.748724        Unleaded   1645 2024-09-30 00:15:00
91099   61478245          Horrocks Mechanical    Independent        22-26 Progress St       Quinalow        QLD            4403     -27.109437      151.622803        Unleaded   1678 2024-09-19 03:56:00
91100   61478247                   IOR Lytton  IOR Petroleum               6 Radar St         Lytton        QLD            4178     -27.429574      153.140804          Diesel   1779 2024-09-29 23:48:00

[1677 rows x 12 columns]

In [15]:
print(last_rows_per_site[last_rows_per_site['SiteId']==61401206])

         SiteId        Site_Name Site_Brand           Sites_Address_Line_1 Site_Suburb Site_State  Site_Post_Code  Site_Latitude  Site_Longitude       Fuel_Type  Price  TransactionDateutc
36565  61401206  U-Go Park Ridge       U-Go  3726-3730 Mt Lindesay Highway  Park Ridge        QLD            4125     -27.696775      153.038071  Premium Diesel   1669 2024-09-30 05:50:00

In [16]:
import pandas as pd

# Step 0: Data Cleaning
cleaned_fuel_data = df[df['Price'] != 9999]

# Remove outliers using the IQR method
Q1 = cleaned_fuel_data['Price'].quantile(0.25)
Q3 = cleaned_fuel_data['Price'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
cleaned_fuel_data = cleaned_fuel_data[(cleaned_fuel_data['Price'] >= lower_bound) & (cleaned_fuel_data['Price'] <= upper_bound)]

# Convert 'TransactionDateutc' to datetime format and truncate to date
cleaned_fuel_data['TransactionDateutc'] = pd.to_datetime(cleaned_fuel_data['TransactionDateutc'], format="%d/%m/%Y %H:%M").dt.date

# Step 1: Aggregating Daily Prices (min, median, max) per fuel type
daily_fuel_prices = cleaned_fuel_data.groupby([pd.Grouper(key='TransactionDateutc'), 'Fuel_Type'])['Price'].agg(['min', 'median', 'max']).reset_index()

# Load crude oil prices and clean up the data
crude_oil_data = pd.read_csv('Crude Oil WTI Futures Historical Data.csv')
crude_oil_data['Date'] = pd.to_datetime(crude_oil_data['Date'], format="%m/%d/%Y").dt.date
crude_oil_data_clean = crude_oil_data[['Date', 'Price']].dropna()

# Merge fuel prices with crude oil data
merged_data = pd.merge(daily_fuel_prices, crude_oil_data_clean, left_on='TransactionDateutc', right_on='Date', how='inner')

# Step 2: Clean TGP Petrol and Diesel Data
tgp_petrol_data = pd.read_csv('Petrol TGP-Table 1.csv')
tgp_diesel_data = pd.read_csv('Diesel TGP-Table 1.csv')

# TGP petrol data
tgp_petrol_data.columns = ['Date', 'Sydney', 'Melbourne', 'Brisbane', 'Adelaide', 'Perth', 'Darwin', 'Hobart', 'National_Average_Petrol']
tgp_petrol_data['Date'] = pd.to_datetime(tgp_petrol_data['Date'], format='%A, %B %d, %Y').dt.date

# TGP diesel data
tgp_diesel_data.columns = ['Date', 'Sydney', 'Melbourne', 'Brisbane', 'Adelaide', 'Perth', 'Darwin', 'Hobart', 'National_Average_Diesel']
tgp_diesel_data['Date'] = pd.to_datetime(tgp_diesel_data['Date'], format='%A, %B %d, %Y').dt.date

# Step 3: Merging with TGP Data

# Merge petrol TGP
merged_data_with_tgp = pd.merge(merged_data, tgp_petrol_data[['Date', 'National_Average_Petrol']], on='Date', how='left')

# Merge diesel TGP
merged_data_with_tgp = pd.merge(merged_data_with_tgp, tgp_diesel_data[['Date', 'National_Average_Diesel']], on='Date', how='left')

# Step 4: Aligning TGP values with Fuel Types

# Create a column that selects Petrol TGP for petrol-based fuels and Diesel TGP for diesel-based fuels
merged_data_with_tgp['TGP'] = merged_data_with_tgp.apply(
    lambda row: row['National_Average_Petrol'] if 'Petrol' in row['Fuel_Type'] or 'Unleaded' in row['Fuel_Type'] or 'PULP' in row['Fuel_Type']
                else row['National_Average_Diesel'] if 'Diesel' in row['Fuel_Type'] else None, axis=1)

merged_data_with_tgp['National_Average_Diesel'] = merged_data_with_tgp['National_Average_Diesel'] * 10
merged_data_with_tgp['National_Average_Petrol'] = merged_data_with_tgp['National_Average_Petrol'] * 10
merged_data_with_tgp['TGP'] = merged_data_with_tgp['TGP'] * 10
# Display the merged dataset with aligned TGP
print(merged_data_with_tgp.head())

  TransactionDateutc       Fuel_Type   min  median   max        Date  Price  National_Average_Petrol  National_Average_Diesel     TGP
0         2024-01-01          Diesel  1735  1899.5  2100  2024-01-01  71.97                   1660.0                   1749.0  1749.0
1         2024-01-01  PULP 95/96 RON  1767  1879.0  2299  2024-01-01  71.97                   1660.0                   1749.0  1660.0
2         2024-01-01     PULP 98 RON  1825  1952.0  2399  2024-01-01  71.97                   1660.0                   1749.0  1660.0
3         2024-01-01  Premium Diesel  1719  1949.0  2199  2024-01-01  71.97                   1660.0                   1749.0  1749.0
4         2024-01-01        Unleaded  1625  1739.0  2099  2024-01-01  71.97                   1660.0                   1749.0  1660.0